dataset_params:
  root_dir: 'data/MNIST/raw'

diffusion_params:
  num_timesteps : 1000
  beta_1 : 0.0001
  beta_T : 0.02

model_params:
  im_channels : 1
  im_size : 28
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  down_samples : [True, True, False]
  time_embedding_dim : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 4

train_params:
  task_name: 'default'
  batch_size: 64
  num_epochs: 40
  num_samples : 100
  num_grid_rows : 10
  lr: 0.0001
  ckpt_name: 'model_31.pt'
